#!/usr/bin/env python3
"""Apply the declarative catalog curation policy without deleting tool pages."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.parse import urlencode

from generate_tool_catalog import load_catalog, public_tools, write_browser_artifacts


SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
QUERY_KEY_RE = re.compile(r"^[a-z][a-z0-9_-]{0,31}$")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    frontend = root / "frontend"
    policy = json.loads((root / "tool-curation.json").read_text(encoding="utf-8"))
    risk_policy = json.loads((root / "tool-risk-policy.json").read_text(encoding="utf-8"))
    generated = json.loads((root / "generated-conversion-tools.json").read_text(encoding="utf-8"))
    redirects = dict(policy["redirects"])
    redirects.update(generated.get("legacy_redirects", {}))
    redirect_queries = policy.get("redirect_queries", {})
    if not isinstance(redirect_queries, dict):
        print("tool-curation.json: redirect_queries must be an object", file=sys.stderr)
        return 1

    risk_by_slug: dict[str, str] = {}
    for group in risk_policy.get("groups", []):
        risk = group.get("risk")
        for slug in group.get("slugs", []):
            previous = risk_by_slug.get(slug)
            if previous is not None and previous != risk:
                print(f"tool-risk-policy.json: conflicting risk for {slug}", file=sys.stderr)
                return 1
            risk_by_slug[slug] = risk
    catalog_path = frontend / "assets" / "tool-catalog.json"
    document, tools = load_catalog(catalog_path)

    keep = set(policy["keep"])
    unlisted = set(policy["unlist"]) | set(redirects) | set(risk_by_slug)
    pages = {page.parent.name for page in (frontend / "tools").glob("*/index.html")}
    for slug in pages:
        if any(slug.startswith(item) for item in policy["unlist_prefixes"]) and slug not in keep:
            unlisted.add(slug)

    unknown = sorted(unlisted - pages)
    if unknown:
        print("Policy references missing pages: " + ", ".join(unknown), file=sys.stderr)
        return 1

    # Preserve quarantined entries and their review metadata in the canonical
    # catalog, but make the publication decision explicit and durable.
    for tool in tools:
        if tool["slug"] in risk_by_slug:
            tool["risk"] = risk_by_slug[tool["slug"]]
        if tool["slug"] in unlisted:
            tool["listed"] = False
    document["tools"] = tools
    catalog_path.write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    write_browser_artifacts(frontend, public_tools(tools, unlisted))

    redirect_lines = [
        "# Generated by scripts/apply_tool_curation.py; do not edit manually."
    ]
    for source, target in sorted(redirects.items()):
        if not SLUG_RE.fullmatch(source) or not SLUG_RE.fullmatch(target):
            print(f"Invalid redirect slug: {source!r} -> {target!r}", file=sys.stderr)
            return 1
        params = redirect_queries.get(source)
        suffix = ""
        if params is not None:
            if (
                not isinstance(params, dict)
                or not params
                or any(
                    not isinstance(key, str)
                    or not QUERY_KEY_RE.fullmatch(key)
                    or not isinstance(value, str)
                    or not SLUG_RE.fullmatch(value)
                    for key, value in params.items()
                )
            ):
                print(f"Invalid redirect query for {source}", file=sys.stderr)
                return 1
            suffix = "?" + urlencode(sorted(params.items()))
        redirect_lines.append(
            f"location = /tools/{source}/ {{ return 301 /tools/{target}/{suffix}; }}"
        )
    (root / "nginx" / "tool-redirects.conf").write_text(
        "\n".join(redirect_lines) + "\n", encoding="utf-8"
    )
    print(f"Unlisted {len(unlisted)} retained pages; generated {len(redirects)} redirects")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
