#!/usr/bin/env python3
"""Apply the declarative catalog curation policy without deleting tool pages."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from validate_tools import parse_registry


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    frontend = root / "frontend"
    policy = json.loads((root / "tool-curation.json").read_text(encoding="utf-8"))
    generated = json.loads((root / "generated-conversion-tools.json").read_text(encoding="utf-8"))
    redirects = dict(policy["redirects"])
    redirects.update(generated.get("legacy_redirects", {}))
    registry = frontend / "assets" / "tools.js"
    prefix, objects, suffix = parse_registry(registry)

    keep = set(policy["keep"])
    unlisted = set(policy["unlist"]) | set(redirects)
    pages = {page.parent.name for page in (frontend / "tools").glob("*/index.html")}
    for slug in pages:
        if any(slug.startswith(item) for item in policy["unlist_prefixes"]) and slug not in keep:
            unlisted.add(slug)

    unknown = sorted(unlisted - pages)
    if unknown:
        print("Policy references missing pages: " + ", ".join(unknown), file=sys.stderr)
        return 1

    retained = [block for slug, block in objects if slug not in unlisted]
    registry.write_text(prefix + "".join(retained) + suffix, encoding="utf-8")

    redirect_lines = [
        "# Generated by scripts/apply_tool_curation.py; do not edit manually."
    ]
    for source, target in sorted(redirects.items()):
        redirect_lines.append(f"location = /tools/{source}/ {{ return 301 /tools/{target}/; }}")
    (root / "nginx" / "tool-redirects.conf").write_text(
        "\n".join(redirect_lines) + "\n", encoding="utf-8"
    )
    print(f"Unlisted {len(unlisted)} retained pages; generated {len(redirects)} redirects")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
