#!/usr/bin/env python3
"""Inject SEO and trust metadata into the homepage and public tool pages.

The canonical JSON catalog is the single source of truth for per-tool metadata.
This script rewrites the built HTML in place so the nginx
image serves fully-formed meta tags with no runtime logic.

Usage: generate_seo.py <frontend_root> <base_url>
  <frontend_root>  path to the frontend/ directory (e.g. frontend)
  <base_url>      absolute site URL without trailing slash (e.g. https://virt.tools)

It inserts a block immediately before </head> in:
  - <frontend_root>/index.html            (homepage: WebSite + SearchAction)
  - <frontend_root>/tools/<slug>/index.html (per tool: WebApplication)

Idempotent: any previously injected block (delimited by SEO BEGIN/END comments)
is removed before re-inserting, so re-runs don't accumulate.
"""
import html
import json
import re
import sys
from pathlib import Path

try:
    from .generate_tool_catalog import public_guidance
except ImportError:  # Direct script execution places scripts/ on sys.path.
    from generate_tool_catalog import public_guidance

SITE_NAME = "Virtual Tools"
HOME_DESC = "A collection of free browser-based tools that run locally and preserve your privacy."
OG_IMAGE = "/assets/og-image.png"
OG_IMAGE_ALT = "Virtual Tools — free, private, browser-based utilities"
BEGIN = "<!-- SEO BEGIN (generated by scripts/generate_seo.py; do not edit) -->"
END = "<!-- SEO END -->"

BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)


def esc_attr(s: str) -> str:
    """Escape a value for use inside an HTML attribute."""
    return html.escape(s or "", quote=True)


def jsonld(obj) -> str:
    """Serialise JSON-LD, escaping characters that could break the <script> context."""
    s = json.dumps(obj, ensure_ascii=False)
    return s.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def load_catalog(root: Path) -> list[dict]:
    """Load public entries and apply curation as a final publication guard."""
    document = json.loads((root / "assets" / "tool-catalog.json").read_text(encoding="utf-8"))
    tools = document.get("tools")
    if not isinstance(tools, list):
        raise RuntimeError("canonical catalog has no tools array")
    project_root = root.parent
    hidden: set[str] = set()
    policy_path = project_root / "tool-curation.json"
    if policy_path.is_file():
        policy = json.loads(policy_path.read_text(encoding="utf-8"))
        keep = set(policy.get("keep", []))
        hidden.update(policy.get("unlist", []))
        hidden.update(policy.get("redirects", {}))
        prefixes = tuple(policy.get("unlist_prefixes", []))
        if prefixes:
            hidden.update(
                page.parent.name
                for page in (root / "tools").glob("*/index.html")
                if page.parent.name.startswith(prefixes) and page.parent.name not in keep
            )
        hidden.difference_update(keep)
    generated_path = project_root / "generated-conversion-tools.json"
    if generated_path.is_file():
        generated = json.loads(generated_path.read_text(encoding="utf-8"))
        hidden.update(generated.get("legacy_redirects", {}))
    return [
        tool for tool in tools
        if isinstance(tool, dict) and tool.get("listed", True) and tool.get("slug") not in hidden
    ]


def meta_tags(*triples: tuple[str, str, str]) -> str:
    # Each triple is (attr_name, attr_value, content) e.g. ("name", "description", "...").
    return "\n".join(
        f'  <meta {a}="{esc_attr(k)}" content="{esc_attr(c)}">'
        for a, k, c in triples if c is not None
    )


def inject(path: Path, block: str) -> None:
    html_text = path.read_text(encoding="utf-8")
    html_text = BLOCK_RE.sub("", html_text)
    # Become the sole owner of the description meta (tool pages have none; the
    # homepage has a hand-written one) so we never emit a duplicate.
    html_text = re.sub(r'[ \t]*<meta\s+name="description"[^>]*>\n?', "", html_text)
    if "</head>" not in html_text:
        raise RuntimeError(f"{path}: no </head> to inject before")
    html_text = html_text.replace("</head>", block + "\n</head>", 1)
    path.write_text(html_text, encoding="utf-8")


def homepage_block(base: str) -> str:
    url = base + "/"
    tags = meta_tags(
        ("name", "description", HOME_DESC),
        ("property", "og:title", SITE_NAME),
        ("property", "og:description", HOME_DESC),
        ("property", "og:type", "website"),
        ("property", "og:url", url),
        ("property", "og:site_name", SITE_NAME),
        ("property", "og:image", base + OG_IMAGE),
        ("property", "og:image:width", "1200"),
        ("property", "og:image:height", "630"),
        ("property", "og:image:alt", OG_IMAGE_ALT),
        ("name", "twitter:card", "summary_large_image"),
        ("name", "twitter:title", SITE_NAME),
        ("name", "twitter:description", HOME_DESC),
        ("name", "twitter:image", base + OG_IMAGE),
    )
    ld = jsonld({
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": SITE_NAME,
        "url": url,
        "potentialAction": {
            "@type": "SearchAction",
            "target": {
                "@type": "EntryPoint",
                "urlTemplate": base + "/?q={search_term_string}",
            },
            "query-input": "required name=search_term_string",
        },
    })
    return (
        BEGIN
        + "\n  <link rel=\"canonical\" href=\"" + esc_attr(url) + "\">\n"
        + tags + "\n"
        + f'  <script type="application/ld+json">{ld}</script>\n'
        + END
    )


def tool_block(base: str, t: dict) -> str:
    slug = t["slug"]
    url = base + "/tools/" + slug + "/"
    name = t.get("name", slug)
    desc = t.get("description", name)
    tags = meta_tags(
        ("name", "description", desc),
        ("property", "og:title", name + " — " + SITE_NAME),
        ("property", "og:description", desc),
        ("property", "og:type", "website"),
        ("property", "og:url", url),
        ("property", "og:site_name", SITE_NAME),
        ("property", "og:image", base + OG_IMAGE),
        ("property", "og:image:width", "1200"),
        ("property", "og:image:height", "630"),
        ("property", "og:image:alt", name + " — " + SITE_NAME),
        ("name", "twitter:card", "summary_large_image"),
        ("name", "twitter:title", name + " — " + SITE_NAME),
        ("name", "twitter:description", desc),
        ("name", "twitter:image", base + OG_IMAGE),
        ("name", "vt:tool-slug", slug),
        ("name", "vt:guidance", public_guidance(t)),
        ("name", "vt:maturity", t.get("maturity", "unreviewed")),
        ("name", "vt:reviewed-at", t.get("reviewedAt") or ""),
        ("name", "vt:method", t.get("method") or ""),
        ("name", "vt:source-count", str(len(t.get("sources") or []))),
        ("name", "vt:test-count", str(len(t.get("testCases") or []))),
    )
    ld = jsonld({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": name,
        "url": url,
        "description": desc,
        "applicationCategory": t.get("category", "Utility") + "Application",
        "operatingSystem": "Any (web browser)",
        "browserRequirements": "Requires JavaScript",
        "isAccessibleForFree": True,
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
    })
    return (
        BEGIN
        + "\n  <link rel=\"canonical\" href=\"" + esc_attr(url) + "\">\n"
        + tags + "\n"
        + f'  <script type="application/ld+json">{ld}</script>\n'
        + END
    )


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_seo.py <frontend_root> <base_url>", file=sys.stderr)
        return 2
    root = Path(sys.argv[1])
    base = sys.argv[2].rstrip("/")

    tools = load_catalog(root)
    if not tools:
        raise RuntimeError(f"no public tools loaded from {root / 'assets' / 'tool-catalog.json'}")

    home = root / "index.html"
    inject(home, homepage_block(base))

    n = 0
    for t in tools:
        page = root / "tools" / t["slug"] / "index.html"
        if page.exists():
            inject(page, tool_block(base, t))
            n += 1
    print(f"Injected SEO into homepage + {n} tool pages (base={base})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
