#!/usr/bin/env python3
"""Validate the canonical catalog, generated registry, routes, and local assets."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from urllib.parse import urlencode

from generate_tool_catalog import (
    CATALOG_FILENAME,
    GENERATED_FILENAME,
    curated_slugs,
    load_catalog,
    public_tools,
    render_browser_registry,
    validate_catalog,
    write_browser_artifacts,
)


LOCAL_REF_RE = re.compile(
    r'<(?:script\b[^>]*\bsrc|link\b[^>]*\bhref)="(/[^"?#]+)', re.IGNORECASE
)
INLINE_SCRIPT_RE = re.compile(
    r"<script(?![^>]*\bsrc=)[^>]*>.*?</script>", re.IGNORECASE | re.DOTALL
)


def load_policy_state(project_root: Path, frontend: Path) -> tuple[set[str], dict[str, str]]:
    policy_path = project_root / "tool-curation.json"
    unlisted: set[str] = set()
    redirects: dict[str, str] = {}
    if not policy_path.is_file():
        return unlisted, redirects
    policy = json.loads(policy_path.read_text(encoding="utf-8"))
    keep = set(policy.get("keep", []))
    unlisted.update(policy.get("unlist", []))
    redirects.update(policy.get("redirects", {}))
    generated_path = project_root / "generated-conversion-tools.json"
    if generated_path.is_file():
        generated = json.loads(generated_path.read_text(encoding="utf-8"))
        redirects.update(generated.get("legacy_redirects", {}))
    unlisted.update(redirects)
    prefixes = tuple(policy.get("unlist_prefixes", []))
    if prefixes:
        for page in (frontend / "tools").glob("*/index.html"):
            slug = page.parent.name
            if slug.startswith(prefixes) and slug not in keep:
                unlisted.add(slug)
    return unlisted - keep, redirects


def problems(root: Path) -> tuple[list[str], int, int]:
    issues: list[str] = []
    project_root = root.parent
    catalog_path = root / "assets" / CATALOG_FILENAME
    try:
        _, tools = load_catalog(catalog_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return [str(exc)], 0, 0
    issues.extend(validate_catalog(tools, root))

    risk_policy_path = project_root / "tool-risk-policy.json"
    if risk_policy_path.is_file():
        risk_policy = json.loads(risk_policy_path.read_text(encoding="utf-8"))
        risk_by_slug = {
            slug: group.get("risk")
            for group in risk_policy.get("groups", [])
            for slug in group.get("slugs", [])
        }
        catalog_by_slug = {tool["slug"]: tool for tool in tools}
        for slug, expected_risk in sorted(risk_by_slug.items()):
            record = catalog_by_slug.get(slug)
            if record is None:
                continue
            if record.get("risk") != expected_risk:
                issues.append(
                    f"canonical risk mismatch for {slug}: "
                    f"{record.get('risk')!r} != {expected_risk!r}"
                )
            if record.get("listed", True):
                issues.append(f"risk-policy tool is not explicitly unlisted: {slug}")

    hidden = curated_slugs(project_root, root)
    public = public_tools(tools, hidden)
    for artifact_issue in write_browser_artifacts(root, public, check=True):
        issues.append(
            artifact_issue.replace(str(project_root) + "/", "")
            + "; run scripts/generate_tool_catalog.py"
        )

    pages = {page.parent.name for page in (root / "tools").glob("*/index.html")}
    registered = {tool["slug"] for tool in public}
    catalog_slugs = {tool["slug"] for tool in tools}
    manually_unlisted = {tool["slug"] for tool in tools if not tool["listed"]}
    unlisted, redirects = load_policy_state(project_root, root)
    allowed_unlisted = unlisted | manually_unlisted

    for slug in sorted(registered - pages):
        issues.append(f"registered tool has no page: {slug}")
    for slug in sorted(pages - catalog_slugs - allowed_unlisted):
        issues.append(f"tool page is neither cataloged nor curated: {slug}")
    for slug in sorted(registered & allowed_unlisted):
        issues.append(f"unlisted tool is still emitted publicly: {slug}")
    for source, target in sorted(redirects.items()):
        if source == target:
            issues.append(f"redirect points to itself: {source}")
        if target not in registered:
            issues.append(f"redirect target is not publicly registered: {source} -> {target}")

    policy = json.loads((project_root / "tool-curation.json").read_text(encoding="utf-8"))
    redirect_queries = policy.get("redirect_queries", {})
    expected_redirect_lines = [
        "# Generated by scripts/apply_tool_curation.py; do not edit manually."
    ]
    for source, target in sorted(redirects.items()):
        params = redirect_queries.get(source)
        suffix = "?" + urlencode(sorted(params.items())) if params is not None else ""
        expected_redirect_lines.append(
            f"location = /tools/{source}/ {{ return 301 /tools/{target}/{suffix}; }}"
        )
    expected_redirect_config = "\n".join(expected_redirect_lines) + "\n"
    redirect_config_path = project_root / "nginx" / "tool-redirects.conf"
    if not redirect_config_path.is_file():
        issues.append("nginx/tool-redirects.conf: generated redirect config is missing")
    elif redirect_config_path.read_text(encoding="utf-8") != expected_redirect_config:
        issues.append(
            "nginx/tool-redirects.conf: generated redirects differ from all declarative "
            "curation/conversion mappings; run scripts/apply_tool_curation.py"
        )

    for page in sorted(root.rglob("*.html")):
        text = page.read_text(encoding="utf-8")
        label = page.relative_to(root)
        if not re.search(r"<title>.+?</title>", text, re.IGNORECASE | re.DOTALL):
            issues.append(f"{label}: missing or empty title")
        if "</head>" not in text.lower() or "</body>" not in text.lower():
            issues.append(f"{label}: missing closing head or body tag")
        markup = INLINE_SCRIPT_RE.sub("", text)
        for ref in LOCAL_REF_RE.findall(markup):
            target = root / ref.lstrip("/")
            if not target.is_file():
                issues.append(f"{label}: missing local asset {ref}")
    return issues, len(tools), len(public)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("frontend", type=Path)
    parser.add_argument("--fix", action="store_true", help="regenerate tools.js before validating")
    args = parser.parse_args()
    root = args.frontend.resolve()
    if args.fix:
        _, tools = load_catalog(root / "assets" / CATALOG_FILENAME)
        hidden = curated_slugs(root.parent, root)
        write_browser_artifacts(root, public_tools(tools, hidden))
    issues, total, public_count = problems(root)
    if issues:
        print("\n".join(issues))
        return 1
    print(f"Validated {total} catalog entries and {public_count} public tool pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
